---
- hosts: aci
  connection: local
  gather_facts: no

  tasks:
  - name: 01 - create tenant
    aci_tenant:
     host: "{{ aci_host }}"
     username: "{{ aci_user }}"
     password: "{{ aci_password }}"
     use_ssl: "{{ aci_use_ssl }}"
     validate_certs: "{{ aci_valid_cert }}"
     tenant: Ansible_First_Tenant
     description: tenant created by Ansible
     state: present
     
  - name: 02 - create vrf
    aci_vrf:
     host: "{{ aci_host }}"
     username: "{{ aci_user }}"
     password: "{{ aci_password }}"
     use_ssl: "{{ aci_use_ssl }}"
     validate_certs: "{{ aci_valid_cert }}"
     vrf: VRF_1
     tenant: Ansible_First_Tenant
     description: vrf created by ansible
     policy_control_preference: enforced
     policy_control_direction: ingress
     state: present

  - name: 03 - Add Bridge Domain
    aci_bd:
     host: "{{ aci_host }}"
     username: "{{ aci_user }}"
     password: "{{ aci_password }}"
     use_ssl: "{{ aci_use_ssl }}"
     validate_certs: "{{ aci_valid_cert }}"
     tenant: Ansible_First_Tenant
     mac_address: 00:22:BD:F8:19:FE
     bd: BD_1
     vrf: VRF_1
     description: bridge domain created by Ansible
     state: present

  - name: 04 - add a subnet with options
    aci_bd_subnet:
     host: "{{ aci_host }}"
     username: "{{ aci_user }}"
     password: "{{ aci_password }}"
     use_ssl: "{{ aci_use_ssl }}"
     validate_certs: "{{ aci_valid_cert }}"
     tenant: Ansible_First_Tenant
     bd: BD_1
     subnet_name: subnets
     description: first subnet
     gateway: 192.168.11.1
     mask: 24
     state: present

  - name: 05 - Add a new ap
    aci_ap:
     host: "{{ aci_host }}"
     username: "{{ aci_user }}"
     password: "{{ aci_password }}"
     use_ssl: "{{ aci_use_ssl }}"
     validate_certs: "{{ aci_valid_cert }}"
     tenant: Ansible_First_Tenant
     ap: sample_app
     description: Application Profile
     state: present

  - name: 06 - Add a new epg
    aci_epg:
     host: "{{ aci_host }}"
     username: "{{ aci_user }}"
     password: "{{ aci_password }}"
     use_ssl: "{{ aci_use_ssl }}"
     validate_certs: "{{ aci_valid_cert }}"
     tenant: Ansible_First_Tenant
     ap: sample_app
     epg: sample_epg
     description: epg
     state: present
     bd: BD_1
